apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-mysql
  namespace: laboratory
  labels:
    name: zabbix-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-mysql
  template:
    metadata:
      labels:
        name: zabbix-mysql
    spec:
      containers:
        - name: mysql
          image: registry.k8s.example.com:5000/mysql:5.7.29
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: logs
              mountPath: /data
            - name: conf
              mountPath: /etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zabbix-mysql-data
        - name: logs
          persistentVolumeClaim:
            claimName: zabbix-mysql-logs
        - name: conf
          configMap:
            name: zabbix-mysql-conf