apiVersion: v1
kind: Service
metadata:
  name: zabbix-mysql
  namespace: laboratory
  labels:
    name: zabbix-mysql
spec:
  type: ClusterIP
  clusterIP: 10.98.126.191
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
  selector:
    name: zabbix-mysql