apiVersion: v1
kind: Service
metadata:
  name: laboratory-svc-jenkins
  namespace: laboratory
  labels:
    name: laboratory-svc-jenkins
spec:
  type: NodePort
  ports:
    - port: 8080        # 服务访问端口
      targetPort: 8080  # 容器端口
      nodePort: 31001   # NodePort，节点上监听的端口
  selector:
    name: laboratory-jenkins