apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: laboratory
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: registry.k8s.example.com:5000/jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /var/jenkins_home
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jenkins