apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: laboratory
  labels:
    name: jenkins
spec:
  type: ClusterIP
  clusterIP: 10.99.167.214
  ports:
    - port: 8080        # 服务访问端口
      targetPort: 8080  # 容器端口
  selector:
    name: jenkins