apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laboratory-pvc-jenkins
  namespace: laboratory
  labels:
    name: laboratory-pvc-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: laboratory-pv-nfs-jenkins