apiVersion: apps/v1
kind: Deployment
metadata:
  name: laboratory-deploy-jenkins
  namespace: laboratory
  labels:
    name: laboratory-deploy-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      name: laboratory-jenkins
  template:
    metadata:
      labels:
        name: laboratory-jenkins
    spec:
      containers:
        - name: laboratory-jenkins
          image: registry.k8s.example.com:5000/jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: laboratory-jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: laboratory-jenkins-data
          persistentVolumeClaim:
            claimName: laboratory-pvc-jenkins