apiVersion: v1
kind: Service
metadata:
  name: training-redis-svc
  namespace: training-20200126
  labels:
    name: pagoda-redis-svc
spec:
  type: NodePort
  ports:
    - port: 6379        # 服务访问端口
      targetPort: 6379  # 容器端口
      nodePort: 30004   # NodePort，节点上监听的端口
  selector:
    name: training-redis