---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-redis-eshop-alimini-api-deploy
  namespace: training-20200126
  labels:
    name: training-redis-eshop-alimini-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: training-redis-eshop-alimini-api
  template:
    metadata:
      labels:
        name: training-redis-eshop-alimini-api
    spec:
      containers:
        - name: training-redis-eshop-alimini-api
          image: registry.k8s.example.com:5000/redis:5.0.7
          resources:
            requests:
              cpu: 100m          #限制cpu的数量为0.1个
              memory: 100Mi      #限制内存为100Mi
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/eshop-alimini-api-reids.conf"] # 配置文件中的daemon值要设置为no。
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: training-redis-eshop-alimini-api-data
              mountPath: /data
            - name: training-redis-eshop-alimini-api-conf
              mountPath: /usr/local/etc/redis/
              readOnly: true
      volumes:
        - name: training-redis-eshop-alimini-api-data
          persistentVolumeClaim:
            claimName: nfs-pvc-training-redis-eshop-alimini-api
        - name: training-redis-eshop-alimini-api-conf
          configMap:
            name: eshop-alimini-api-reids.conf


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-redis-eshop-oms-api-deploy
  namespace: training-20200126
  labels:
    name: training-redis-eshop-oms-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: training-redis-eshop-oms-api
  template:
    metadata:
      labels:
        name: training-redis-eshop-oms-api
    spec:
      containers:
        - name: training-redis-eshop-oms-api
          image: registry.k8s.example.com:5000/redis:5.0.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/eshop-oms-api-reids.conf"] # 配置文件中的daemon值要设置为no。
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: training-redis-eshop-oms-api-data
              mountPath: /data
            - name: training-redis-eshop-oms-api-conf
              mountPath: /usr/local/etc/redis/
              readOnly: true
      volumes:
        - name: training-redis-eshop-oms-api-data
          persistentVolumeClaim:
            claimName: nfs-pvc-training-redis-eshop-oms-api
        - name: training-redis-eshop-oms-api-conf
          configMap:
            name: eshop-oms-api-reids.conf