apiVersion: v1
kind: Service
metadata:
  name: training-mysql-svc
  namespace: training-20200126
  labels:
    name: pagoda-mysql-svc
spec:
  type: NodePort
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
      nodePort: 30003   # NodePort，节点上监听的端口
  selector:
    name: training-mysql