apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagoda-jenkins-hostpath-pvc
  labels:
    name: pagoda-jenkins-hostpath-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi