apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagoda-jenkins-nfs-pvc
  labels:
    name: pagoda-jenkins-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi