apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: laboratory
  labels:
    name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
      nodePort: 31002   # NodePort，节点上监听的端口
  selector:
    name: mysql