apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: laboratory
  labels:
    name: mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "laboratory-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-logs
  namespace: laboratory
  labels:
    name: mysql-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: "laboratory-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi