apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: laboratory
  labels:
    name: mysql
data:
  MYSQL_ROOT_PASSWORD: "Iam007..."
  MYSQL_DATABASE: "public-data-warehouse"
  MYSQL_USER: "Roy"
  MYSQL_PASSWORD: "IamRoy?King:007"