apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-training-ingress-frd
  namespace: training-20200126
  labels:
    name: nfs-pvc-training-ingress-frd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: nfs-pv-training-ingress-frd