apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exp-redis-import-nfs-pvc
  labels:
    name: exp-redis-import-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi