apiVersion: v1
kind: Service
metadata:
  name: exp-redis-export-svc
  labels:
    name: exp-redis-export-svc
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: exp-redis-export