---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: laboratory
  labels:
    name: redis
spec:
  type: NodePort
  ports:
    - port: 6379        # 服务访问端口
      targetPort: 6379  # 容器端口
      nodePort: 31000   # NodePort，节点上监听的端口
  selector:
    name: redis