---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: laboratory
  labels:
    name: redis
  annotations:
    volume.beta.kubernetes.io/storage-class: "laboratory-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi