---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: laboratory
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      initContainers:
        - name: sysctl
          image: registry.k8s.example.com:5000/busybox:1.31.1
          command: ["sysctl"]
          args: ["-w", "net.core.somaxconn=65535"]
          securityContext:
            privileged: true
      containers:
        - name: redis
          image: registry.k8s.example.com:5000/redis:5.0.7
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/redis.conf"] # 配置文件中的daemon值要设置为no。
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /usr/local/etc/redis/
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
        - name: conf
          configMap:
            name: redis.conf