---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: laboratory
  labels:
    name: redis
spec:
  type: ClusterIP
  clusterIP: 10.97.72.56
  ports:
    - port: 6379        # 服务访问端口
      targetPort: 6379  # 容器端口
  selector:
    name: redis