apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul-server-cluster
  namespace: training-20200126
  labels:
    name: consul-server-cluster
spec:
  serviceName: consul-server-cluster
  replicas: 3
  selector:
    matchLabels:
      name: consul-server-cluster
  template:
    metadata:
      name: consul-server-cluster
      labels:
        name: consul-server-cluster
    spec:
      containers:
        - name: consul-server-cluster
          image: registry.k8s.example.com:5000/consul:1.6.2
          args:
               - "agent"
               - "-server"
               - "-bootstrap-expect=3"
               - "-ui"
               - "-data-dir=/consul/data"
               - "-bind=0.0.0.0"
               - "-client=0.0.0.0"
               - "-advertise=$(PODIP)"
               - "-retry-join=consul-server-cluster-0.consul-server-cluster.$(NAMESPACE).svc.cluster.local"
               - "-retry-join=consul-server-cluster-1.consul-server-cluster.$(NAMESPACE).svc.cluster.local"
               - "-retry-join=consul-server-cluster-2.consul-server-cluster.$(NAMESPACE).svc.cluster.local"
               - "-domain=cluster.local"
               - "-disable-host-node-id"
          volumeMounts:
              - name: consul-server-cluster-data
                mountPath: /consul/data
          env:
              - name: PODIP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
          ports:
              - containerPort: 8500
                name: ui-port
              - containerPort: 8400
                name: alt-port
              - containerPort: 53
                name: udp-port
              - containerPort: 8443
                name: https-port
              - containerPort: 8080
                name: http-port
              - containerPort: 8301
                name: serflan
              - containerPort: 8302
                name: serfwan
              - containerPort: 8600
                name: consuldns
              - containerPort: 8300
                name: server
      volumes:
        - name: consul-server-cluster-data
          persistentVolumeClaim:
            claimName: nfs-pvc-training-consul-server-cluster