---
apiVersion: v1
kind: Service
metadata:
    name: consul-server-cluster-svc
    namespace: training-20200126
    labels:
      name: consul-server-cluster-svc
spec:
    type: NodePort
    ports:
      - name: http
        port: 8500
        targetPort: 8500
        nodePort: 31000

      - name: https
        port: 8443
        targetPort: 8443
        nodePort: 31001

      - name: rpc
        port: 8400
        targetPort: 8400
        nodePort: 31002

      - name: serflan-tcp
        protocol: "TCP"
        port: 8301
        targetPort: 8301
        nodePort: 31003

      - name: serflan-udp
        protocol: "UDP"
        port: 8301
        targetPort: 8301
        nodePort: 31004

      - name: serfwan-tcp
        protocol: "TCP"
        port: 8302
        targetPort: 8302
        nodePort: 31005

      - name: serfwan-udp
        protocol: "UDP"
        port: 8302
        targetPort: 8302
        nodePort: 31006

      - name: server
        port: 8300
        targetPort: 8300
        nodePort: 31007

      - name: consuldns
        port: 8600
        targetPort: 8600
        nodePort: 31008
    selector:
     app: consul-server-cluster
