apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-training-redis
  namespace: training-20200126
  labels:
    name: nfs-pv-training-redis
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.255.252
    path: /data/k8s_nfs_data/training/redis/standalone