apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-training-redis
  namespace: training-20200126
  labels:
    name: nfs-pvc-training-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: nfs-pv-training-redis