---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-training-redis-eshop-alimini-api
  namespace: training-20200126
  labels:
    name: nfs-pv-training-redis-eshop-alimini-api
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.255.252
    path: /data/k8s_nfs_data/training/redis/eshop-alimini-api


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-training-redis-eshop-oms-api
  namespace: training-20200126
  labels:
    name: nfs-pv-training-redis-eshop-oms-api
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.255.252
    path: /data/k8s_nfs_data/training/redis/eshop-oms-api