apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix
  namespace: laboratory
  labels:
    name: zabbix
data:
  # 初始化zabbix-mysql数据库所需变量。
  MYSQL_ROOT_PASSWORD: "IamPassword000..."
  MYSQL_DATABASE: "zabbix"
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zabbix"

  # zabbix-server及zabbix-agent端所需变量，此变量应用于运行在POD中的容器。
  ZBX_SERVER_NAME: "zabbix.k8s.example.com"
  ZBX_SERVER_HOST: "zabbix-server.laboratory.svc.cluster.local" # 使用zabbix-server的svc作为入口地址。
  ZBX_SERVER_PORT: "10051"
  ZBX_SERVER_LISTENIP: "0.0.0.0"
  ZBX_DB_SERVER_HOST: "zabbix-mysql.laboratory.svc.cluster.local"
  ZBX_DB_SERVER_PORT: "3306"
  ZBX_MYSQL_DATABASE: "zabbix"
  ZBX_MYSQL_USER: "zabbix"
  ZBX_MYSQL_PASSWORD: "zabbix"
  ZBX_PHP_TZ: "Asia/Shanghai"

  # zabbix-agent端所需变量，此变量应用于运行在DS状态的容器。
  # 此时需要将原POD中运行的zabbix-server端口通过第三方负载均衡代理出来。
  DS_ZBX_SERVER_NAME: "192.168.255.0/24"
  DS_ZBX_SERVER_PORT: "10051"
  DS_ZBX_PASSIVE_ALLOW: "true"
  DS_ZBX_PASSIVESERVERS: "192.168.255.0/24"