apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-training-jenkins
  namespace: training-20200126
  labels:
    name: nfs-pvc-training-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: nfs-pv-training-jenkins