apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: laboratory
  labels:
    name: zabbix-web
spec:
  type: ClusterIP
  clusterIP: 10.98.126.193
  ports:
    - port: 80        # 服务访问端口
      targetPort: 80  # 容器端口
  selector:
    name: zabbix-web