apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: laboratory
  labels:
    name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-web
  template:
    metadata:
      labels:
        name: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: registry.k8s.example.com:5000/zabbix/zabbix-web-apache-mysql:centos-4.0.17
          ports:
            - containerPort: 80
          env:
            - name: ZBX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_SERVER_NAME
            - name: ZBX_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_SERVER_HOST
            - name: ZBX_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_SERVER_PORT
            - name: DB_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_DB_SERVER_HOST
            - name: DB_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_DB_SERVER_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_MYSQL_PASSWORD
            - name: PHP_TZ
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: ZBX_PHP_TZ