apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    daemonset: zabbix-agent
  name: zabbix-agent
  namespace: laboratory
spec:
  selector:
    matchLabels:
      daemonset: zabbix-agent
  template:
    metadata:
      labels:
        daemonset: zabbix-agent
    spec:
      containers:
        - name: zabbix-agent
          env:
            - name: ZBX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZBX_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: DS_ZBX_SERVER_PORT
            - name: ZBX_PASSIVE_ALLOW
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: DS_ZBX_PASSIVE_ALLOW
            - name: ZBX_PASSIVESERVERS
              valueFrom:
                configMapKeyRef:
                  name: zabbix
                  key: DS_ZBX_PASSIVESERVERS
          image: registry.k8s.example.com:5000/zabbix/zabbix-agent:centos-4.0.17
          imagePullPolicy: Always
          ports:
          - containerPort: 10050 #使用hostport方式暴露地址
            hostPort: 10050
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet