---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-training-consul-server-cluster
  namespace: training-20200126
  labels:
    name: nfs-pv-training-consul-server-cluster
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.255.252
    path: /data/k8s_nfs_data/training/consul-server-cluster