---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-training-consul-server-cluster
  namespace: training-20200126
  labels:
    name: nfs-pvc-training-consul-server-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: nfs-pv-training-consul-server-cluster