apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: laboratory
  labels:
    name: zabbix-server
spec:
  type: ClusterIP
  clusterIP: "None"
  ports:
    - port: 10051        # 服务访问端口
      targetPort: 10051
  selector:
    name: zabbix-server